### ISSUE TITLE
SPF Record for Mandrill (and maybe for Gmail?)

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#352]
It'll prevent the ugly "via ______" addendum from appearing next to our emails.

https://support.google.com/a/answer/33786?hl=en

**Comment by harrislapiroff** [comment]
Probably this is not a brambling issue, actually.

**Comment by melinath** [comment]
I've set up spf & dkim records for mandrill / littleweaverweb.com. We'll have to wait for propagation to test, though.

**Comment by melinath** [comment]
DKIM is working, and our domain is verified with Mandrill. SPF I had to redo, because apparently it has to be a TXT record rather than an SPF record - [SPF is (apparently) deprecated](http://webmasters.stackexchange.com/questions/27910/txt-vs-spf-record-for-google-servers-spf-record-either-or-both).

**Comment by melinath** [comment]
SPF is set up.
