### ISSUE TITLE
Actually disable clicking on unavailable items

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#360]
Right now they look unavailable, but you can still click on them and get an error. This is silly.

**Comment by chigby** [comment]
It's possible this has changed since February 2015, but here's my understanding of our current situation: 

1. Items which have passed their available date are not shown in the shop at all.
2. Items which have sold out are colored grey. If you click them, you get a notice saying "That item is sold out."

Is the change proposed by this issue to remove sold out items from the store entirely, matching the behavior of (1), or to remove the notice and make it so clicking on grey items does nothing?

This is just for my clarification. Both of these changes seem like a small amount of work.

**Comment by harrislapiroff** [comment]
I think the latter is the preferable case for sold out items. Organizers generally want potential attendees to know if passes are sold out, because otherwise potential attendees will assume they were never made available and will email the organizers to ask.

**Comment by melinath** [comment]
Could we also have a hover text saying what's wrong? I.e. does this play well with items that are unavailable because of time as well as unavailable because of running out?

**Comment by harrislapiroff** [comment]
I think unavailable because of time it makes more sense to hide them, because they're more likely to be stuff like "Early bird registration" or registration that hasn't opened yet.

**Comment by harrislapiroff** [comment]
(I.e., the way it is already is good, I believe.)

**Comment by melinath** [comment]
But early bird should still be displayed (potentially) even after it's no longer available, even if it isn't displayed *before* it's available.

**Comment by harrislapiroff** [comment]
My intuition is that it's a rare case that an organizer will care if early bird shows up after it's expired. I think it's a common case that an organizer will care that registration still shows up as sold out after it's sold out.

**Comment by melinath** [comment]
kk
