### ISSUE TITLE
Dashboard event listing link to shop regardless of whether registered

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#417]
ie, have the title of the event link to the shop, and have the "edit registration" button retain how it currently works

**Comment by harrislapiroff** [comment]
+1

**Comment by melinath** [comment]
I'm ambivalent.

**Comment by melinath** [comment]
@JCattera What this ticket means.

On the main page ("Your Events") there's a listing of all active events that you can register for. Currently, clicking on the name of the event and clicking on the "register" / "manage registration" buttons does the same thing: it sends you to your order summary page. If you don't have an order yet, you get redirected to the event shop.

So the task at hand is to make it so that the event name always links directly to the event shop instead.
