### ISSUE TITLE
Offer .xls files

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#572]
Yeah, .csv files should be sufficient but people like to get things in familiar formats. (And this would ensure proper import, which people have maybe been having trouble with? #558) We could use https://pypi.python.org/pypi/xlwt

**Comment by chigby** [comment]
Here's the thing: are we sure we need this?
 
 * Right now, our data is just columns and rows. We are not taking advantage of any Excel-specific features or formatting. Changing the format would be entirely cosmetic.
 * Notwithstanding a bug in a 10 year old piece of software (#558), CSV files are supported by all versions of Excel, as well as Open Office, Numbers, Google Drive, Gnumeric, awk, and whatever else. XLS files are a less compatible version of the same thing.
 * Is XLS more familiar to people than XLSX, which has been the format Excel has used since 2007. Do we want to offer both? Could lead to even more confusion.
 * If people are interesting in doing interesting things to our data with Excel, let's find out what those things are. Maybe we could help? Offer derived numbers natively, provide an integration to services that they're piping the numbers into, offering Excel-specific spreadsheets with formulas and stuff that are useful? Add some value to what they're doing, you know!

**Comment by melinath** [comment]
If we were to do this, it would be .xlsx for maximum familiarity. Personally I'd be fine with leaving it as just CSVs for now.

**Comment by harrislapiroff** [comment]
I think it's pretty important to provide people formats that they're familiar with, regardless of functionality, for both convenience and comfort's sake. A person's computer is not guaranteed to automatically know what to open a CSV file in, but if it has Excel installed, it will know how to open an XLS. And Excel, unlike Numbers and the rest, is an "industry standard" :stuck_out_tongue_winking_eye:. Our users are not necessary tech-savvy and the word CSV throws many people.

XLSX and not XLS would be sufficient from my perspective.

**Comment by harrislapiroff** [comment]
Ftr here are the formats Google Sheets provides. I don't think we need to go this far, but you can see they also provide multiple formats that have essentially the same functionality (esp. TSV and CSV)

![screenshot 2015-09-17 17 19 14](https://cloud.githubusercontent.com/assets/296631/9946286/4ddb427c-5d60-11e5-9303-4cddbe9366d1.png)

**Comment by harrislapiroff** [comment]
https://pypi.python.org/pypi/XlsxWriter looks nice and pretty easy

**Comment by chigby** [comment]
The thing about Google Sheets is it is itself a spreadsheet program and is capable of advanced formatting. A CSV exported from Google Sheets is just bare data, while the Excel file will contain the additional features that Excel supports. Our CSV files and Excel files will be identical.

Another comparison might be Mail Chimp, which exports subscriber information as CSVs only. See http://kb.mailchimp.com/lists/managing-subscribers/view-or-export-a-list

**Comment by harrislapiroff** [comment]
Right, I was pointing out Google Sheets not because they provide xlsx, but because they provide both csv and tsv.

**Comment by melinath** [comment]
Resolved with merge of #631.
