### ISSUE TITLE
Better security for users without accounts

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#592]
Short order codes can be nice for some things, but it's not great for security for anonymous users. Really we should have 20 char codes. That would also necessitate a shorter identifier for the order, though. I'd suggest a per-event order number - essentially an index of where the order was created.

**Comment by harrislapiroff** [comment]
I don't think this is actually going to improve security _that_ much. It will definitely make brute-forcing harder, but I think brute-forcing is as relevant to us as these potential attacks:

* intercepting a URL with a MiTM attack (This seems like the least likely, since we have HTTPS on, but...)
* discovering a URL in browser history. (Say someone orders, or even just _looks at_ a Dancerfly ticket on a public computer.)
* acquiring a URL from an email someone forwarded to you. (Say I forward my receipt to my rideshare group to confirm that I'm registered and someone, on a whim, clicks the link to view it on site.)

These all seem like more likely attacks to me and they won't be fixed by longer codes. I also would advise against consecutive numbered order identifiers. Using random codes means that if I am checking in with an order code I'm less likely to accidentally copy down a wrong code (say, off by one digit) and have it accepted as valid or be able to maliciously give the code of the another person. (Sure, yeah, my order number is "00043".)

**Comment by harrislapiroff** [comment]
Or if I'm an organizer giving another organizer a list of order codes to be refunded, or marking a check with an order code on it is paid, etc.

**Comment by melinath** [comment]
Just to have these copied over, these are security improvements along these lines that @harrislapiroff had suggested in another thread:

>1. Have the receipt be the only confirmation the user has. Don't give them a permanent URL.
>2. Automatically create an account for even anonymous users. The permanent link is now just a temporary URL. The first time they try to view/edit their information on site, force them to create a password and retire the temporary URL. (IIRC this is what eventbrite does.)
>3. Don't give users a permanent URL, but allow them to request a one-time-use temporary auth URL sent to their email address anytime, which expires after 24 hours. (This would manage all tickets associated with that email address.)

**Comment by melinath** [comment]
Resolving this by first implementing #246 (claiming anonymous orders from confirmed accounts) and then requiring login / creation if someone visits the URL.

**Comment by chigby** [comment]
Just a thought: would it make sense to require the order code _and_ their email address to see the order details? This is how Expedia does it.
![screen shot 2015-09-15 at 17 22 58](https://cloud.githubusercontent.com/assets/561931/9890530/7b3eb566-5bce-11e5-9d41-f98737a09dc7.png)

**Comment by melinath** [comment]
So the first half is done. What I'd propose for the second half:

- [ ] Don't allow access by URL period, only by session.
- [ ] When the URL is used, provide a signup form.
- [ ] On the verification page, add a link to the order claiming page, probably similar to the notification at the top of the account settings page.
- [ ] Delete incomplete orders completely when they expire. (I think there's a separate ticket for that.)

**Comment by harrislapiroff** [comment]
That proposal sounds great to me.

I would also like to notify people upon registration that they _have_ orders made previously, but that they have to confirm their email address first. Related to [this comment](https://github.com/littleweaver/django-brambling/pull/618#issuecomment-140614127):

> It might be nice if you could see that there are unclaimed orders, even if you email address isn't confirmed. Just not be allowed to view or claim them. (That could theoretically be considered a security hole, since you could determine if someone had orders, but that seems like a pretty small potential information leak.)

I think, especially if this is a process we indicate that users should follow to edit old orders, it will be confusing to register and not have your old orders show up immediately.

**Comment by melinath** [comment]
Yeah, I think you're right.

**Comment by chigby** [comment]
After reading through the parts of brambling dealing with orders, my intuition is that we will no longer need/want the `code` in the URL for getting the order summary and we should redirect requests to urls with the code to ones without (or to a signup page if it is an anonymous order). Do either of you see a problem with this? Then we either from the session or from the extant order for the logged-in user.

**Comment by melinath** [comment]
+1
