### ISSUE TITLE
given name / surname

### ISSUE THREAD

**Issue by feonixf** [littleweaver/django-brambling#605]
I think it's waaaaaay more common (= less confusing) to use First and Last.

https://dancerfly.com/demo/demo-event/order/attendees/add/

**Comment by harrislapiroff** [comment]
We debated this a lot when we first built this, but I'm ready to concede that First Name/Last Name the way of least confusion for our audience. "Surname" _basically_ already means last name anyway and isn't much of an improvement on it. Providing the name order options is probably sufficient to account for different cultural naming conventions.

Ultimately the right place to account for this linguistically would be in l10n since naming conventions are often tied to language.

**Comment by melinath** [comment]
Just had an event complain about this...

**Comment by harrislapiroff** [comment]
Let's make this change. This is going to touch a lot of code probably. Offhand I suspect it will probably require changes to:

* models
* forms
* templates
* tables
* maybe even any views or utilities that refer to these fields?

When you change the names of the fields on the models, you'll also need to [make and run new migrations](https://docs.djangoproject.com/en/1.9/topics/migrations/).
