### ISSUE TITLE
Duplicate charges

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#658]
A few people have gotten double-charged for their orders - probably from double-clicking the payment button. We should very much fix that. Probably just by doing a 'disable this button after click' thing.

**Comment by chigby** [comment]
Do you think disabling the button is enough? I feel like this is important enough to guard against multiple submissions on the server side.

**Comment by harrislapiroff** [comment]
IMO disabling the button is enough. This isn't really a malicious attack, so there aren't going to be people deliberately submitting multiple requests to the server-side, as long as the interface prevents accidental submission.

Plus, if for whatever reason someone did still double-submit, it's pretty easy to fix since refunds are so easy.

**Comment by melinath** [comment]
This is very confirmed. I got it to give me *four* transactions by clicking fast enough :-p
