### ISSUE TITLE
Create discount form broken

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#784]
Steps to reproduce:

1. Go the the organizer interface of an event with no discounts
2. Click the "Create Discount +" button
3. Try to fill out the form

The form will have all disabled fields. This view (/org/event/discount/create/) is actually no longer necessary, since the discount list view (/org/event/discount/) now includes the discount form. This should be solved by removing the view and having the dashboard link direct to the discount list view.

**Comment by chigby** [comment]
I think the problem here is the `discount_form` view not knowing about the user's permissions. In my testing, editing a discount also results in an entirely disabled form with no save button. We can potentially remove the obsolete views as well, but fixing the permissions I think will fix this problem.

**Comment by harrislapiroff** [comment]
Yeah, good catch. Alex ran into that this morning and I was just about to report it as well. :)
